### ISSUE TITLE
Can't get high Div. score

### ISSUE THREAD

**Issue by Wonderdch** [smrashid20/DeepAltTrip#1]
Thank your share.

When I run code with your default configurations, I can only get Div. = **0.6**, which far less than the value (**0.766**) mentioned by your paper.

**Comment by HiromasaYamanishi** [comment]
Regarding this, in the paper, since the diversity is 1 when Length=3, they are “evaluating by excluding the first and last POIs.” On the other hand, in this code, they are “evaluating including the first and last POIs.” Is my understanding correct?
